version: "3.8"

services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TITLE=Obsidian
    volumes:
      - obsidian_data:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    shm_size: "1gb"
    
volumes:
  obsidian_data:
